package manual

type ServiceGroup struct {
	PromotionMarketTargetService
	WmsKpiSummary2MiService
	WmsKpi2023SummaryMiService
	WmsLogisticsPcsDetailMiService
	WmsLogisticsPcsSummaryMiService
	WmsLogisticsPcs2023MiService
	WmsLogisticsRateMonthsService
	WmsLogisticsProviderMiService
	WmsLogisticsModeTransportMiService
	WmsLogisticsSalebycountryMiService
	WmsLogisticsStoragefeeMiService
	OmsCnSalesTargetDailyService
	OmsCnChannelSalesService
	WmsLogisticsTailfeeMiService
}
