package manual

type RouterGroup struct {
	PromotionMarketTargetRouter
	WmsKpiSummary2MiRouter
	WmsKpi2023SummaryMiRouter
	WmsLogisticsPcsDetailMiRouter
	WmsLogisticsPcsSummaryMiRouter
	WmsLogisticsPcs2023MiRouter
	WmsLogisticsRateMonthsRouter
	WmsLogisticsProviderMiRouter
	WmsLogisticsModeTransportMiRouter
	WmsLogisticsSalebycountryMiRouter
	WmsLogisticsStoragefeeMiRouter
	OmsCnSalesTargetDailyRouter
	OmsCnChannelSalesRouter
	WmsLogisticsTailfeeMiRouter
}
