package manual

type ApiGroup struct {
	PromotionMarketTargetApi
	WmsKpiSummary2MiApi
	WmsKpi2023SummaryMiApi
	WmsLogisticsPcsDetailMiApi
	WmsLogisticsPcsSummaryMiApi
	WmsLogisticsPcs2023MiApi
	WmsLogisticsRateMonthsApi
	WmsLogisticsProviderMiApi
	WmsLogisticsModeTransportMiApi
	WmsLogisticsSalebycountryMiApi
	WmsLogisticsStoragefeeMiApi
	OmsCnSalesTargetDailyApi
	OmsCnChannelSalesApi
	WmsLogisticsTailfeeMiApi
}
